---
id: Group
name: Group
full: User groups library
description: A library for managing and accessing user group systems.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Group
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha2
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/util: ^3
      horde/support: ^3
  optional:
    composer:
      horde/cache: ^3
      horde/db: ^3
      horde/ldap: ^3
      horde/test: ^3
